### ISSUE TITLE
failed behat and phpunit tests

### ISSUE THREAD

**Issue by ehsan42** [ethz-let/moodle-qtype_mtf#16]
The recent 2 commits

https://github.com/ethz-let/moodle-qtype_mtf/commit/fe50df693bd5938e6bd8a1274c528e5f5fab87a6
https://github.com/ethz-let/moodle-qtype_mtf/commit/2212c856f1ed3e3f5a9150c16c5f0051494e069c

have broken the following behat/phpunit tests below.  We are currently on Moodle 3.11.  Can a seperate MOODLE_STABLE_311 branch be created to the Moodle 4.0 changes so the behat tests continue to work.

behat***********************

Go Parallel / Behat Tests / Step 5.Testcase 22, 23        Error Details           And I press "id_submitbutton": Moodle exception: Exception - Notice: Undefined property: stdClass::$answernumbering in [dirroot]/question/type/mtf/questiontype.php on line 271 More information about this error  Exception - Notice: Undefined property: stdClass::$answernumbering in [dirroot]/question/type/mtf/questiontype.php on line 271 More information about this error        ×      Debug info:    Error code: generalexceptionmessage  (Exception) | 44 sec | 1
-- | -- | --
Go Parallel / Behat Tests / Step 5.Testcase 22        Error Details           And I press "id_submitbutton": Moodle exception: Exception - Notice: Undefined property: stdClass::$answernumbering in [dirroot]/question/type/mtf/questiontype.php on line 271 More information about this error  Exception - Notice: Undefined property: stdClass::$answernumbering in [dirroot]/question/type/mtf/questiontype.php on line 271 More information about this error        ×      Debug info:    Error code: generalexceptionmessage  (Exception) | 36 sec | 1
Go Parallel / Behat Tests / Step 7.Testcase 10, 11        Error Details           And I press "id_updatebutton": Moodle exception: Exception - Notice: Undefined property: stdClass::$answernumbering in [dirroot]/question/type/mtf/questiontype.php on line 271 More information about this error  Exception - Notice: Undefined property: stdClass::$answernumbering in [dirroot]/question/type/mtf/questiontype.php on line 271 More information about this error        ×      Debug info:    Error code: generalexceptionmessage  (Exception) | 12 sec | 1
Go Parallel / Behat Tests / Step 7.Testcase 10, 11        Error Details           And I press "id_updatebutton": Moodle exception: Exception - Notice: Undefined property: stdClass::$answernumbering in [dirroot]/question/type/mtf/questiontype.php on line 271 More information about this error  Exception - Notice: Undefined property: stdClass::$answernumbering in [dirroot]/question/type/mtf/questiontype.php on line 271 More information about this error        ×      Debug info:    Error code: generalexceptionmessage  (Exception) | 13 sec | 1
Go Parallel / Behat Tests / Step 3.Testcase 16        Error Details           And I press "id_submitbutton": Moodle exception: Exception - Notice: Undefined property: stdClass::$answernumbering in [dirroot]/question/type/mtf/questiontype.php on line 271 More information about this error  Exception - Notice: Undefined property: stdClass::$answernumbering in [dirroot]/question/type/mtf/questiontype.php on line 271 More information about this error        ×      Debug info:    Error code: generalexceptionmessage  (Exception) | 30 sec | 1
Go Parallel / Behat Tests / Step 6.Testcase 10, 11, 19        Error Details           And I press "id_updatebutton": Moodle exception: Exception - Notice: Undefined property: stdClass::$answernumbering in [dirroot]/question/type/mtf/questiontype.php on line 271 More information about this error  Exception - Notice: Undefined property: stdClass::$answernumbering in [dirroot]/question/type/mtf/questiontype.php on line 271 More information about this error        ×      Debug info:    Error code: generalexceptionmessage  (Exception) | 24 sec | 1
Go Parallel / Behat Tests / Step 1.Testcase 1,3,4        Error Details           And "Multiple tries" "link" should exist: Link matching locator "Multiple tries" not found. (Behat\Mink\Exception\ElementNotFoundException) | 28 sec | 1
Go Parallel / Behat Tests / Step 1.Testcase 7        Error Details           And I press "id_submitbutton": Moodle exception: Exception - Notice: Undefined property: stdClass::$answernumbering in [dirroot]/question/type/mtf/questiontype.php on line 271 More information about this error  Exception - Notice: Undefined property: stdClass::$answernumbering in [dirroot]/question/type/mtf/questiontype.php on line 271 More information about this error        ×      Debug info:    Error code: generalexceptionmessage  (Exception) | 1 min 29 sec | 1
Go Parallel / Behat Tests / Step 1.Testcase 8        Error Details           And I add a "Multiple True False (ETH)" question filling the form with:: Moodle exception: Exception - Notice: Undefined property: stdClass::$answernumbering in [dirroot]/question/type/mtf/questiontype.php on line 271 More information about this error  Exception - Notice: Undefined property: stdClass::$answernumbering in [dirroot]/question/type/mtf/questiontype.php on line 271 More information about this error        ×      Debug info:    Error code: generalexceptionmessage  (Exception) | 41 sec | 1
Go Parallel / Behat Tests / Step 1.Testcase 5, 6        Error Details           And I add a "Multiple True False (ETH)" question filling the form with:: Moodle exception: Exception - Notice: Undefined property: stdClass::$answernumbering in [dirroot]/question/type/mtf/questiontype.php on line 271 More information about this error  Exception - Notice: Undefined property: stdClass::$answernumbering in [dirroot]/question/type/mtf/questiontype.php on line 271 More information about this error        ×      Debug info:    Error code: generalexceptionmessage  (Exception) | 18 sec | 1
Go Parallel / Behat Tests / Step 1.Testcase 8        Error Details           And I press "id_submitbutton": Moodle exception: Exception - Notice: Undefined property: stdClass::$answernumbering in [dirroot]/question/type/mtf/questiontype.php on line 271 More information about this error  Exception - Notice: Undefined property: stdClass::$answernumbering in [dirroot]/question/type/mtf/questiontype.php on line 271 More information about this error        ×      Debug info:    Error code: generalexceptionmessage  (Exception) | 15 sec | 1
Go Parallel / Behat Tests / Step 1.Testcase 12        Error Details           And I press "id_updatebutton": Moodle exception: Exception - Notice: Undefined property: stdClass::$answernumbering in [dirroot]/question/type/mtf/questiontype.php on line 271 More information about this error  Exception - Notice: Undefined property: stdClass::$answernumbering in [dirroot]/question/type/mtf/questiontype.php on line 271 More information about this error        ×      Debug info:    Error code: generalexceptionmessage  (Exception)

[Go Parallel / Behat Tests / Step 5.Testcase 22, 23](https://jenkins.automation.ucl.ac.uk/job/moodle/job/candidate-builds/job/moodle-1819/job/PREVIEW_311_REBASE/68/testReport/(root)/Step%205/Go_Parallel___Behat_Tests___Testcase_22__23/)
 Error Details

And I press "id_submitbutton": Moodle exception: Exception - Notice: Undefined property: stdClass::$answernumbering in [dirroot]/question/type/mtf/questiontype.php on line 27[1](https://jenkins.automation.ucl.ac.uk/job/moodle/job/candidate-builds/job/moodle-1819/job/PREVIEW_311_REBASE/68/) More information about this error

Exception - Notice: Undefined property: stdClass::$answernumbering in [dirroot]/question/type/mtf/questiontype.php on line 271
More information about this error

    
×
    
Debug info: 
 
Error code: generalexceptionmessage
 (Exception)

	44 sec	1
 [Go Parallel / Behat Tests / Step 5.Testcase 22](https://jenkins.automation.ucl.ac.uk/job/moodle/job/candidate-builds/job/moodle-1819/job/PREVIEW_311_REBASE/68/testReport/(root)/Step%205/Go_Parallel___Behat_Tests___Testcase_22/)
 Error Details

And I press "id_submitbutton": Moodle exception: Exception - Notice: Undefined property: stdClass::$answernumbering in [dirroot]/question/type/mtf/questiontype.php on line 27[1](https://jenkins.automation.ucl.ac.uk/job/moodle/job/candidate-builds/job/moodle-1819/job/PREVIEW_311_REBASE/68/) More information about this error

Exception - Notice: Undefined property: stdClass::$answernumbering in [dirroot]/question/type/mtf/questiontype.php on line 271
More information about this error

    
×
    
Debug info: 
 
Error code: generalexceptionmessage
 (Exception)

	36 sec	1
 [Go Parallel / Behat Tests / Step 7.Testcase 10, 11](https://jenkins.automation.ucl.ac.uk/job/moodle/job/candidate-builds/job/moodle-1819/job/PREVIEW_311_REBASE/68/testReport/(root)/Step%207/Go_Parallel___Behat_Tests___Testcase_10__11/)
 Error Details

And I press "id_updatebutton": Moodle exception: Exception - Notice: Undefined property: stdClass::$answernumbering in [dirroot]/question/type/mtf/questiontype.php on line 27[1](https://jenkins.automation.ucl.ac.uk/job/moodle/job/candidate-builds/job/moodle-1819/job/PREVIEW_311_REBASE/68/) More information about this error

Exception - Notice: Undefined property: stdClass::$answernumbering in [dirroot]/question/type/mtf/questiontype.php on line 271
More information about this error

    
×
    
Debug info: 
 
Error code: generalexceptionmessage
 (Exception)

	12 sec	1
 [Go Parallel / Behat Tests / Step 7.Testcase 10, 11](https://jenkins.automation.ucl.ac.uk/job/moodle/job/candidate-builds/job/moodle-1819/job/PREVIEW_311_REBASE/68/testReport/(root)/Step%207/Go_Parallel___Behat_Tests___Testcase_10__11_2/)
 Error Details

And I press "id_updatebutton": Moodle exception: Exception - Notice: Undefined property: stdClass::$answernumbering in [dirroot]/question/type/mtf/questiontype.php on line 27[1](https://jenkins.automation.ucl.ac.uk/job/moodle/job/candidate-builds/job/moodle-1819/job/PREVIEW_311_REBASE/68/) More information about this error

Exception - Notice: Undefined property: stdClass::$answernumbering in [dirroot]/question/type/mtf/questiontype.php on line 271
More information about this error

    
×
    
Debug info: 
 
Error code: generalexceptionmessage
 (Exception)

	13 sec	1
 [Go Parallel / Behat Tests / Step 3.Testcase 16](https://jenkins.automation.ucl.ac.uk/job/moodle/job/candidate-builds/job/moodle-1819/job/PREVIEW_311_REBASE/68/testReport/(root)/Step%203/Go_Parallel___Behat_Tests___Testcase_16/)
 Error Details

And I press "id_submitbutton": Moodle exception: Exception - Notice: Undefined property: stdClass::$answernumbering in [dirroot]/question/type/mtf/questiontype.php on line 27[1](https://jenkins.automation.ucl.ac.uk/job/moodle/job/candidate-builds/job/moodle-1819/job/PREVIEW_311_REBASE/68/) More information about this error

Exception - Notice: Undefined property: stdClass::$answernumbering in [dirroot]/question/type/mtf/questiontype.php on line 271
More information about this error

    
×
    
Debug info: 
 
Error code: generalexceptionmessage
 (Exception)

	30 sec	1
 [Go Parallel / Behat Tests / Step 6.Testcase 10, 11, 19](https://jenkins.automation.ucl.ac.uk/job/moodle/job/candidate-builds/job/moodle-1819/job/PREVIEW_311_REBASE/68/testReport/(root)/Step%206/Go_Parallel___Behat_Tests___Testcase_10__11__19/)
 Error Details

And I press "id_updatebutton": Moodle exception: Exception - Notice: Undefined property: stdClass::$answernumbering in [dirroot]/question/type/mtf/questiontype.php on line 27[1](https://jenkins.automation.ucl.ac.uk/job/moodle/job/candidate-builds/job/moodle-1819/job/PREVIEW_311_REBASE/68/) More information about this error

Exception - Notice: Undefined property: stdClass::$answernumbering in [dirroot]/question/type/mtf/questiontype.php on line 271
More information about this error

    
×
    
Debug info: 
 
Error code: generalexceptionmessage
 (Exception)

	24 sec	1
 [Go Parallel / Behat Tests / Step 1.Testcase 1,3,4](https://jenkins.automation.ucl.ac.uk/job/moodle/job/candidate-builds/job/moodle-1819/job/PREVIEW_311_REBASE/68/testReport/(root)/Step%201/Go_Parallel___Behat_Tests___Testcase_1_3_4/)
 Error Details

And "Multiple tries" "link" should exist: Link matching locator "Multiple tries" not found. (Behat\Mink\Exception\ElementNotFoundException)

	28 sec	[1](https://jenkins.automation.ucl.ac.uk/job/moodle/job/candidate-builds/job/moodle-1819/job/PREVIEW_311_REBASE/68/)
 [Go Parallel / Behat Tests / Step 1.Testcase 7](https://jenkins.automation.ucl.ac.uk/job/moodle/job/candidate-builds/job/moodle-1819/job/PREVIEW_311_REBASE/68/testReport/(root)/Step%201/Go_Parallel___Behat_Tests___Testcase_7/)
 Error Details

And I press "id_submitbutton": Moodle exception: Exception - Notice: Undefined property: stdClass::$answernumbering in [dirroot]/question/type/mtf/questiontype.php on line 27[1](https://jenkins.automation.ucl.ac.uk/job/moodle/job/candidate-builds/job/moodle-1819/job/PREVIEW_311_REBASE/68/) More information about this error

Exception - Notice: Undefined property: stdClass::$answernumbering in [dirroot]/question/type/mtf/questiontype.php on line 271
More information about this error

    
×
    
Debug info: 
 
Error code: generalexceptionmessage
 (Exception)

	1 min 29 sec	1
 [Go Parallel / Behat Tests / Step 1.Testcase 8](https://jenkins.automation.ucl.ac.uk/job/moodle/job/candidate-builds/job/moodle-1819/job/PREVIEW_311_REBASE/68/testReport/(root)/Step%201/Go_Parallel___Behat_Tests___Testcase_8/)
 Error Details

And I add a "Multiple True False (ETH)" question filling the form with:: Moodle exception: Exception - Notice: Undefined property: stdClass::$answernumbering in [dirroot]/question/type/mtf/questiontype.php on line 27[1](https://jenkins.automation.ucl.ac.uk/job/moodle/job/candidate-builds/job/moodle-1819/job/PREVIEW_311_REBASE/68/) More information about this error

Exception - Notice: Undefined property: stdClass::$answernumbering in [dirroot]/question/type/mtf/questiontype.php on line 271
More information about this error

    
×
    
Debug info: 
 
Error code: generalexceptionmessage
 (Exception)

	41 sec	1
 [Go Parallel / Behat Tests / Step 1.Testcase 5, 6](https://jenkins.automation.ucl.ac.uk/job/moodle/job/candidate-builds/job/moodle-1819/job/PREVIEW_311_REBASE/68/testReport/(root)/Step%201/Go_Parallel___Behat_Tests___Testcase_5__6/)
 Error Details

And I add a "Multiple True False (ETH)" question filling the form with:: Moodle exception: Exception - Notice: Undefined property: stdClass::$answernumbering in [dirroot]/question/type/mtf/questiontype.php on line 27[1](https://jenkins.automation.ucl.ac.uk/job/moodle/job/candidate-builds/job/moodle-1819/job/PREVIEW_311_REBASE/68/) More information about this error

Exception - Notice: Undefined property: stdClass::$answernumbering in [dirroot]/question/type/mtf/questiontype.php on line 271
More information about this error

    
×
    
Debug info: 
 
Error code: generalexceptionmessage
 (Exception)

	18 sec	1
 [Go Parallel / Behat Tests / Step 1.Testcase 8](https://jenkins.automation.ucl.ac.uk/job/moodle/job/candidate-builds/job/moodle-1819/job/PREVIEW_311_REBASE/68/testReport/(root)/Step%201/Go_Parallel___Behat_Tests___Testcase_8_2/)
 Error Details

And I press "id_submitbutton": Moodle exception: Exception - Notice: Undefined property: stdClass::$answernumbering in [dirroot]/question/type/mtf/questiontype.php on line 27[1](https://jenkins.automation.ucl.ac.uk/job/moodle/job/candidate-builds/job/moodle-1819/job/PREVIEW_311_REBASE/68/) More information about this error

Exception - Notice: Undefined property: stdClass::$answernumbering in [dirroot]/question/type/mtf/questiontype.php on line 271
More information about this error

    
×
    
Debug info: 
 
Error code: generalexceptionmessage
 (Exception)

	15 sec	1
 [Go Parallel / Behat Tests / Step 1.Testcase 12](https://jenkins.automation.ucl.ac.uk/job/moodle/job/candidate-builds/job/moodle-1819/job/PREVIEW_311_REBASE/68/testReport/(root)/Step%201/Go_Parallel___Behat_Tests___Testcase_12/)
 Error Details

And I press "id_updatebutton": Moodle exception: Exception - Notice: Undefined property: stdClass::$answernumbering in [dirroot]/question/type/mtf/questiontype.php on line 271 More information about this error

Exception - Notice: Undefined property: stdClass::$answernumbering in [dirroot]/question/type/mtf/questiontype.php on line 271
More information about this error

    
×
    
Debug info: 
 
Error code: generalexceptionmessage
 (Exception)

phpunit****************************************************

Go Parallel / PHPUnit Tests / qtype_mtf_test.test_question_saving_question_one with data set #0        Stack Trace           qtype_mtf_test::test_question_saving_question_one with data set #0 ('question_one') Undefined property: stdClass::$answernumbering  /var/www/html/question/type/mtf/questiontype.php:271 /var/www/html/question/type/questiontypebase.php:474 /var/www/html/question/type/mtf/tests/questiontype_test.php:257 /var/www/html/lib/phpunit/classes/advanced_testcase.php:80 phpvfscomposer:///var/www/html/vendor/phpunit/phpunit/phpunit:97 | 0.32 sec | 1
-- | -- | --
Go Parallel / PHPUnit Tests / qtype_mtf_test.test_question_saving_question_one with data set #1        Stack Trace           qtype_mtf_test::test_question_saving_question_one with data set #1 ('question_two') Undefined property: stdClass::$answernumbering  /var/www/html/question/type/mtf/questiontype.php:271 /var/www/html/question/type/questiontypebase.php:474 /var/www/html/question/type/mtf/tests/questiontype_test.php:257 /var/www/html/lib/phpunit/classes/advanced_testcase.php:80 phpvfscomposer:///var/www/html/vendor/phpunit/phpunit/phpunit:97 | 0.33 sec | 1
Go Parallel / PHPUnit Tests / qtype_mtf_test.test_get_question_options        Stack Trace           qtype_mtf_test::test_get_question_options Undefined property: stdClass::$answernumbering  /var/www/html/question/type/mtf/questiontype.php:271 /var/www/html/question/type/questiontypebase.php:474 /var/www/html/question/type/mtf/tests/questiontype_test.php:323 /var/www/html/lib/phpunit/classes/advanced_testcase.php:80 phpvfscomposer:///var/www/html/vendor/phpunit/phpunit/phpunit:97

[Go Parallel / PHPUnit Tests / qtype_mtf_test.test_question_saving_question_one with data set #0](https://jenkins.automation.ucl.ac.uk/job/moodle/job/candidate-builds/job/moodle-1819/job/PREVIEW_311_REBASE/68/testReport/(root)/qtype_mtf_test/Go_Parallel___PHPUnit_Tests___test_question_saving_question_one_with_data_set__0/)
 Stack Trace

qtype_mtf_test::test_question_saving_question_one with data set #0 ('question_one')
Undefined property: stdClass::$answernumbering

/var/www/html/question/type/mtf/questiontype.php:27[1](https://jenkins.automation.ucl.ac.uk/job/moodle/job/candidate-builds/job/moodle-1819/job/PREVIEW_311_REBASE/68/)
/var/www/html/question/type/questiontypebase.php:474
/var/www/html/question/type/mtf/tests/questiontype_test.php:257
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80
phpvfscomposer:///var/www/html/vendor/phpunit/phpunit/phpunit:97

	0.32 sec	1
 [Go Parallel / PHPUnit Tests / qtype_mtf_test.test_question_saving_question_one with data set #1](https://jenkins.automation.ucl.ac.uk/job/moodle/job/candidate-builds/job/moodle-1819/job/PREVIEW_311_REBASE/68/testReport/(root)/qtype_mtf_test/Go_Parallel___PHPUnit_Tests___test_question_saving_question_one_with_data_set__1/)
 Stack Trace

qtype_mtf_test::test_question_saving_question_one with data set #[1](https://jenkins.automation.ucl.ac.uk/job/moodle/job/candidate-builds/job/moodle-1819/job/PREVIEW_311_REBASE/68/) ('question_two')
Undefined property: stdClass::$answernumbering

/var/www/html/question/type/mtf/questiontype.php:271
/var/www/html/question/type/questiontypebase.php:474
/var/www/html/question/type/mtf/tests/questiontype_test.php:257
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80
phpvfscomposer:///var/www/html/vendor/phpunit/phpunit/phpunit:97

	0.33 sec	1
 [Go Parallel / PHPUnit Tests / qtype_mtf_test.test_get_question_options](https://jenkins.automation.ucl.ac.uk/job/moodle/job/candidate-builds/job/moodle-1819/job/PREVIEW_311_REBASE/68/testReport/(root)/qtype_mtf_test/Go_Parallel___PHPUnit_Tests___test_get_question_options/)
 Stack Trace

qtype_mtf_test::test_get_question_options
Undefined property: stdClass::$answernumbering

/var/www/html/question/type/mtf/questiontype.php:271
/var/www/html/question/type/questiontypebase.php:474
/var/www/html/question/type/mtf/tests/questiontype_test.php:323
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80
phpvfscomposer:///var/www/html/vendor/phpunit/phpunit/phpunit:97

**Comment by nexterday** [comment]
Hi, we are not yet done with behat tests as they need to be reworked for moodle v4.x. For now, please continue to use the stable release for moodle 3.x.

thanks for your patience.
