### ISSUE TITLE
Copy of MTF-question will delete original question

### ISSUE THREAD

**Issue by AntonT76** [ethz-let/moodle-qtype_mtf#20]
Hello,

I have found a strange issue during copying MTF questions in Moodle 3.9 with MTF version 3.2 for Moodle 3.4+ (2021092900): in some cases the original MTF question will be deleted:
- open a course and question bank
- create a MTF question called "my question 1"
- click on "save changes"
- click on "my question 1", edit - duplicate --> the new question will be opened
- edit some settings: change title to "my question 2", do some other changes
- click on "save changes"

Result: "my question 1" isn't available any more, but "my question 2" exists.

It could be related to the autosave function in Moodle. If you wait until autosave will done, the original question get lost. If you click "save changes" before autosave, it will work. 

PS: I did some other tests with the Moodle Core question type True/False - I can't reproduce the error, maybe it is only related to MTF question type.

br, Anton

**Comment by nexterday** [comment]
Hi Anton, the version in question is a very old one. But to assure you:
1. Duplicate is processed by moodle core. No involvement from the plugin.
2. Autosave is also processed by moodle core.

there is a high chance, given that it didnt happen with other qtypes, that either you have the wrong version or you have corrupt question data.

right now we support for 3.11 and 4.x

**Comment by AntonT76** [comment]
Hi @nexterday 

I used the newest version of MTF in Moodle Plugin directory: https://moodle.org/plugins/qtype_mtf/versions which is named as "3.2 for Moodle 3.4+ (2021092900)". Does this version also support Moodle 4.*?

I testet this issue again with this plugin version and other MTF-questions on Moodle 3.9 and also on Moodle 3.11 - I could no longer reproduce the error. So it seems to be that it was a problem with this specific question.

br Anton
