### ISSUE TITLE
Add clear choice to mtf question type v2

### ISSUE THREAD

**Issue by NavidDaxon** [ethz-let/moodle-qtype_mtf#22]
Hi @tkorner and @nexterday
I know default mtf question type doesn't have negative point and it wouldn't be a problem to choose the answers and go on
But I rewrite the subpoint methode and I added negative point by getting isanswered class value and write the negative point for this type of question by my self thats why Iam looking for a way that students could clear their choices like Single choice type
Is there any way I could add a button or something that the student could clear or rest the radio button that choose before for each question or option
Thank you for responding.
Previous issue : https://github.com/ethz-let/moodle-qtype_mtf/issues/21

**Comment by tkorner** [comment]
sorry, i was to fast in closing. Here is the answer I just submitted in #21 too.
***
some weeks ago, @phillipImhof mentioned comparable plan in this issue: https://github.com/ethz-let/moodle-qtype_mtf/issues/19 . Probably you could work on that together?
As mentioned there and above. We are happy to work on pull requests as long as there is the chance to use it without negative points by default.

**Comment by NavidDaxon** [comment]
Yes we could help each other why not.
I was searching for a solution I found this in moodles forum https://moodle.org/mod/forum/discuss.php?d=354680
I was trying to use this for this question type but it doesn't work and the clear button doesn't shown could you help me to use this or other method you suggest for this.
Maybe I am doing the steps wrong I don't know
How can I use this or anything else for this type of question.
I need to solve this by the end of the day that's why Iam so hurry🥲

**Comment by PhilippImhof** [comment]
Just stumbled on this, the tagging did not work. I will gladly take this into consideration when preparing the PR as described in #19, I think it will not be a big deal.

Regarding UX, I'd need to know how you would prefer this to be done: 
* have three radios (true, false, no answer)
* have two radios (true, false) and a button (clear)
* leave the points as they are now and have a global (clear all) button at the bottom
* leave the points as they are now and add a dropdown (to select which row) and a button to clear the selected row

IMHO, the first variant would be the best, but it will change the visual interface quite a lot for everybody. It might be useful to have that as an option in the question then? (With the default being off, as it is now.)
