### ISSUE TITLE
Missing versioning and tags lead to confusion

### ISSUE THREAD

**Issue by Menrath** [ethz-let/moodle-qtype_mtf#29]
Hello,

thirst of all thanks a lot for developling, mantaining and sharing this plugin!

As I can see in the version.php [lasts commit](https://github.com/ethz-let/moodle-qtype_mtf/commit/f22a130ca1159dedd19de05a7ce9871f15655101) you have tagged the version as 4.3, which I can guess that this may indicate support an being tested within the ETH Zürich for Moodle 4.3 support.

**If that is true** I would like to encourage you to use the https://moodledev.io/docs/apis/commonfiles/version.php#supported-versions key which is a much clearer indicator.

Furthermore, at least from my point of view, it is very helpful to see a corresponding tag/commit id for each version released on moodle.org: https://moodle.org/plugins/qtype_mtf/4-possible-from-moodle-3.11-transitional/29350 under _Version control information_, means setting the `VCS tag` (e.g., look here https://moodle.org/plugins/qtype_mtf/4-possible-from-moodle-3.11-transitional/29350).

Thanks again and greetings from Graz University.

**Comment by nexterday** [comment]
Ciao Menrath, 

We are reworking all re-versioning and branchings if you noticed that. During branching a lot of changes are shown publicly and some info might be missing or confusing - please bare with us until its done.

Cheers
