### ISSUE TITLE
Support for Moddle 4.3+

### ISSUE THREAD

**Issue by Shotte** [ethz-let/moodle-qtype_mtf#31]
Hi there, is there any chance to get an update of your question type with an official support for newer Moodle releases >4.3, e.g 4.4 or even better 4.5 LTS?

Thank you!

**Comment by nexterday** [comment]
Hi, you can find them here: https://github.com/ethz-let/moodle-qtype_mtf/branches

they will be updated too on moodle.org during the update window.

**Comment by Shotte** [comment]
Thank you for your quick response!
